steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile.cloudrun
      - -t
      - ${_IMAGE}
      - --build-arg
      - PARVA_PRECOMPUTE=${_PARVA_PRECOMPUTE}
      - .

images:
  - ${_IMAGE}

substitutions:
  _IMAGE: parva-backend-public-demo:latest
  _PARVA_PRECOMPUTE: "0"
