"""
Expand Non-Hindu Festival Rules
================================

Adds 55+ new festival rules across Buddhist, Kirat, Tharu, ethnic,
and Islamic categories to match Master Plan coverage targets.

Categories targeted:
  - Buddhist: 20+ observances (Saga Dawa, Losar variants, Parinirvana, etc.)
  - Kirat: 12+ festivals (Sakela, Lhosar variants, Chasok Tangnam, etc.)
  - Tharu: 8+ festivals (Maghi, Jitiya, Astimki, etc.)
  - Islamic: 5+ observances (Eid ul-Fitr, Eid ul-Adha, etc.)
  - Multi-tradition: 5+ cross-cutting observances
"""

import json
import sys
from pathlib import Path
from datetime import datetime, timezone

RULES_PATH = Path("/Users/rohanbasnet14/Documents/Project_Parva/data/festivals/festival_rules_v4.json")

# ─── New rules to add ──────────────────────────────────────

NEW_RULES = [
    # ═══════════════════════════════════════════════════════
    # BUDDHIST OBSERVANCES (20 new)
    # ═══════════════════════════════════════════════════════
    {
        "festival_id": "saga-dawa",
        "name_en": "Saga Dawa",
        "name_ne": "साग दावा",
        "rule_type": "lunar",
        "status": "computed",
        "confidence": "high",
        "category": "buddhist",
        "importance": "major",
        "tradition": "tibetan_buddhist",
        "regions": ["mustang", "manang", "dolpo", "solukhumbu"],
        "rule_family": "lunar_month_tithi",
        "profile_ids": [],
        "has_variant_profiles": False,
        "source": "expansion_v4",
        "engine": "v2_lunar_month",
        "notes": "Fourth month of Tibetan calendar. Commemorates Buddha's birth, enlightenment, and parinirvana. Full moon is holiest day.",
        "tags": ["v4", "buddhist", "tibetan"],
        "rule": {"lunar_month": "Jestha", "tithi": 15, "paksha": "shukla", "adhik_policy": "skip"},
    },
    {
        "festival_id": "sonam-lhosar",
        "name_en": "Sonam Lhosar",
        "name_ne": "सोनाम ल्होसार",
        "rule_type": "lunar",
        "status": "computed",
        "confidence": "high",
        "category": "buddhist",
        "importance": "national",
        "tradition": "tamang",
        "regions": ["nuwakot", "rasuwa", "dhading", "sindhupalchok"],
        "rule_family": "lunar_month_tithi",
        "profile_ids": [],
        "has_variant_profiles": False,
        "source": "expansion_v4",
        "engine": "v2_lunar_month",
        "notes": "Tamang New Year, celebrated on first day of new moon in Magh.",
        "tags": ["v4", "tamang", "lhosar"],
        "rule": {"lunar_month": "Magh", "tithi": 1, "paksha": "shukla", "adhik_policy": "skip"},
    },
    {
        "festival_id": "gyalpo-lhosar",
        "name_en": "Gyalpo Lhosar",
        "name_ne": "ग्याल्पो ल्होसार",
        "rule_type": "lunar",
        "status": "computed",
        "confidence": "high",
        "category": "buddhist",
        "importance": "regional",
        "tradition": "sherpa",
        "regions": ["solukhumbu", "sankhuwasabha", "taplejung"],
        "rule_family": "lunar_month_tithi",
        "profile_ids": [],
        "has_variant_profiles": False,
        "source": "expansion_v4",
        "engine": "v2_lunar_month",
        "notes": "Sherpa/Tibetan New Year, based on Tibetan calendar.",
        "tags": ["v4", "sherpa", "tibetan", "lhosar"],
        "rule": {"lunar_month": "Falgun", "tithi": 1, "paksha": "shukla", "adhik_policy": "skip"},
    },
    {
        "festival_id": "parinirvana-day",
        "name_en": "Parinirvana Day",
        "name_ne": "परिनिर्वाण दिवस",
        "rule_type": "lunar",
        "status": "computed",
        "confidence": "high",
        "category": "buddhist",
        "importance": "major",
        "tradition": "buddhist",
        "regions": ["lumbini", "kapilvastu"],
        "rule_family": "lunar_month_tithi",
        "profile_ids": [],
        "has_variant_profiles": False,
        "source": "expansion_v4",
        "engine": "v2_lunar_month",
        "notes": "Death of Gautama Buddha. Observed on Magh Purnima in Theravada tradition.",
        "tags": ["v4", "buddhist"],
        "rule": {"lunar_month": "Magh", "tithi": 15, "paksha": "shukla", "adhik_policy": "skip"},
    },
    {
        "festival_id": "dharma-chakra-pravartan",
        "name_en": "Dharma Chakra Pravartan",
        "name_ne": "धर्मचक्र प्रवर्तन दिवस",
        "rule_type": "lunar",
        "status": "computed",
        "confidence": "high",
        "category": "buddhist",
        "importance": "major",
        "tradition": "buddhist",
        "regions": ["lumbini"],
        "rule_family": "lunar_month_tithi",
        "profile_ids": [],
        "has_variant_profiles": False,
        "source": "expansion_v4",
        "engine": "v2_lunar_month",
        "notes": "First sermon of Buddha at Sarnath. Ashadh Purnima.",
        "tags": ["v4", "buddhist"],
        "rule": {"lunar_month": "Ashadh", "tithi": 15, "paksha": "shukla", "adhik_policy": "skip"},
    },
    {
        "festival_id": "lhabab-duchen",
        "name_en": "Lhabab Duchen",
        "name_ne": "ल्हाबाब दुचेन",
        "rule_type": "lunar",
        "status": "computed",
        "confidence": "medium",
        "category": "buddhist",
        "importance": "regional",
        "tradition": "tibetan_buddhist",
        "regions": ["mustang", "manang"],
        "rule_family": "lunar_month_tithi",
        "profile_ids": [],
        "has_variant_profiles": False,
        "source": "expansion_v4",
        "engine": "v2_lunar_month",
        "notes": "Buddha's descent from Tushita heaven. 22nd day of 9th Tibetan month.",
        "tags": ["v4", "tibetan", "buddhist"],
        "rule": {"lunar_month": "Kartik", "tithi": 7, "paksha": "krishna", "adhik_policy": "skip"},
    },
    {
        "festival_id": "chokor-duchen",
        "name_en": "Chokor Duchen",
        "name_ne": "चोकोर दुचेन",
        "rule_type": "lunar",
        "status": "computed",
        "confidence": "medium",
        "category": "buddhist",
        "importance": "regional",
        "tradition": "tibetan_buddhist",
        "regions": ["mustang", "manang", "dolpo"],
        "rule_family": "lunar_month_tithi",
        "profile_ids": [],
        "has_variant_profiles": False,
        "source": "expansion_v4",
        "engine": "v2_lunar_month",
        "notes": "Turning of the Wheel of Dharma. 4th day of 6th Tibetan month.",
        "tags": ["v4", "tibetan", "buddhist"],
        "rule": {"lunar_month": "Shrawan", "tithi": 4, "paksha": "shukla", "adhik_policy": "skip"},
    },
    {
        "festival_id": "nyungne",
        "name_en": "Nyungne Fasting Practice",
        "name_ne": "न्युङ्ने",
        "rule_type": "lunar",
        "status": "computed",
        "confidence": "medium",
        "category": "buddhist",
        "importance": "observance",
        "tradition": "tibetan_buddhist",
        "regions": ["mustang", "manang", "solukhumbu"],
        "rule_family": "lunar_month_tithi",
        "profile_ids": [],
        "has_variant_profiles": False,
        "source": "expansion_v4",
        "engine": "v2_lunar_month",
        "notes": "Purification fasting on Saga Dawa full moon approach.",
        "tags": ["v4", "tibetan", "buddhist"],
        "rule": {"lunar_month": "Jestha", "tithi": 14, "paksha": "shukla", "adhik_policy": "skip"},
    },
    {
        "festival_id": "monlam-chenmo",
        "name_en": "Monlam Chenmo (Great Prayer Festival)",
        "name_ne": "मोनलम चेन्मो",
        "rule_type": "lunar",
        "status": "computed",
        "confidence": "medium",
        "category": "buddhist",
        "importance": "regional",
        "tradition": "tibetan_buddhist",
        "regions": ["mustang", "boudha"],
        "rule_family": "lunar_month_tithi",
        "profile_ids": [],
        "has_variant_profiles": False,
        "source": "expansion_v4",
        "engine": "v2_lunar_month",
        "notes": "Great Prayer Festival, first 15 days of Tibetan New Year.",
        "tags": ["v4", "tibetan", "buddhist"],
        "rule": {"lunar_month": "Falgun", "tithi": 15, "paksha": "shukla", "adhik_policy": "skip"},
    },
    {
        "festival_id": "saka-dawa-full-moon",
        "name_en": "Saka Dawa Full Moon (Vesak)",
        "name_ne": "साक दावा पूर्णिमा",
        "rule_type": "lunar",
        "status": "computed",
        "confidence": "high",
        "category": "buddhist",
        "importance": "major",
        "tradition": "theravada",
        "regions": ["lumbini", "swayambhu", "boudha"],
        "rule_family": "lunar_month_tithi",
        "profile_ids": [],
        "has_variant_profiles": False,
        "source": "expansion_v4",
        "engine": "v2_lunar_month",
        "notes": "Most sacred day in Theravada - triple gem day.",
        "tags": ["v4", "buddhist", "theravada"],
        "rule": {"lunar_month": "Baishakh", "tithi": 15, "paksha": "shukla", "adhik_policy": "skip"},
    },
    {
        "festival_id": "abhidhamma-day",
        "name_en": "Abhidhamma Day",
        "name_ne": "अभिधम्म दिवस",
        "rule_type": "lunar",
        "status": "computed",
        "confidence": "medium",
        "category": "buddhist",
        "importance": "observance",
        "tradition": "theravada",
        "regions": ["lumbini"],
        "rule_family": "lunar_month_tithi",
        "profile_ids": [],
        "has_variant_profiles": False,
        "source": "expansion_v4",
        "engine": "v2_lunar_month",
        "notes": "End of Kathina (Vassa). Ashwin Purnima.",
        "tags": ["v4", "buddhist", "theravada"],
        "rule": {"lunar_month": "Ashwin", "tithi": 15, "paksha": "shukla", "adhik_policy": "skip"},
    },
    {
        "festival_id": "kathina-ceremony",
        "name_en": "Kathina Ceremony",
        "name_ne": "कठिन दान",
        "rule_type": "lunar",
        "status": "computed",
        "confidence": "medium",
        "category": "buddhist",
        "importance": "observance",
        "tradition": "theravada",
        "regions": ["lumbini", "kapilvastu"],
        "rule_family": "lunar_month_tithi",
        "profile_ids": [],
        "has_variant_profiles": False,
        "source": "expansion_v4",
        "engine": "v2_lunar_month",
        "notes": "Robe-offering ceremony after Vassa rains retreat.",
        "tags": ["v4", "buddhist", "theravada"],
        "rule": {"lunar_month": "Kartik", "tithi": 15, "paksha": "shukla", "adhik_policy": "skip"},
    },
    {
        "festival_id": "vassa-start",
        "name_en": "Vassa (Rains Retreat) Begins",
        "name_ne": "वर्षा वास आरम्भ",
        "rule_type": "lunar",
        "status": "computed",
        "confidence": "medium",
        "category": "buddhist",
        "importance": "observance",
        "tradition": "theravada",
        "regions": ["lumbini"],
        "rule_family": "lunar_month_tithi",
        "profile_ids": [],
        "has_variant_profiles": False,
        "source": "expansion_v4",
        "engine": "v2_lunar_month",
        "notes": "Start of 3-month monsoon retreat for monks. Ashadh Purnima.",
        "tags": ["v4", "buddhist"],
        "rule": {"lunar_month": "Ashadh", "tithi": 15, "paksha": "shukla", "adhik_policy": "skip"},
    },
    {
        "festival_id": "boudha-stupa-anniversary",
        "name_en": "Boudhanath Festivals",
        "name_ne": "बौद्धनाथ महोत्सव",
        "rule_type": "lunar",
        "status": "computed",
        "confidence": "medium",
        "category": "buddhist",
        "importance": "local",
        "tradition": "tibetan_buddhist",
        "regions": ["boudha", "kathmandu"],
        "rule_family": "lunar_month_tithi",
        "profile_ids": [],
        "has_variant_profiles": False,
        "source": "expansion_v4",
        "engine": "v2_lunar_month",
        "notes": "Annual celebrations at Boudhanath stupa.",
        "tags": ["v4", "buddhist"],
        "rule": {"lunar_month": "Chaitra", "tithi": 15, "paksha": "shukla", "adhik_policy": "skip"},
    },
    {
        "festival_id": "losar-dolpo",
        "name_en": "Dolpo Losar",
        "name_ne": "डोल्पो ल्होसार",
        "rule_type": "lunar",
        "status": "computed",
        "confidence": "medium",
        "category": "buddhist",
        "importance": "regional",
        "tradition": "bonpo",
        "regions": ["dolpo"],
        "rule_family": "lunar_month_tithi",
        "profile_ids": [],
        "has_variant_profiles": False,
        "source": "expansion_v4",
        "engine": "v2_lunar_month",
        "notes": "Trans-Himalayan New Year in Dolpo region, Bon-Buddhist tradition.",
        "tags": ["v4", "bonpo", "lhosar"],
        "rule": {"lunar_month": "Magh", "tithi": 1, "paksha": "shukla", "adhik_policy": "skip"},
    },
    {
        "festival_id": "mani-rimdu",
        "name_en": "Mani Rimdu",
        "name_ne": "मणि रिम्दु",
        "rule_type": "lunar",
        "status": "computed",
        "confidence": "medium",
        "category": "buddhist",
        "importance": "regional",
        "tradition": "sherpa",
        "regions": ["solukhumbu", "tengboche"],
        "rule_family": "lunar_month_tithi",
        "profile_ids": [],
        "has_variant_profiles": False,
        "source": "expansion_v4",
        "engine": "v2_lunar_month",
        "notes": "Sherpa sacred dance festival at Tengboche monastery.",
        "tags": ["v4", "sherpa", "buddhist"],
        "rule": {"lunar_month": "Kartik", "tithi": 10, "paksha": "shukla", "adhik_policy": "skip"},
    },
    {
        "festival_id": "dumji",
        "name_en": "Dumji Festival",
        "name_ne": "दुम्जी पर्व",
        "rule_type": "lunar",
        "status": "computed",
        "confidence": "medium",
        "category": "buddhist",
        "importance": "regional",
        "tradition": "sherpa",
        "regions": ["solukhumbu", "namche"],
        "rule_family": "lunar_month_tithi",
        "profile_ids": [],
        "has_variant_profiles": False,
        "source": "expansion_v4",
        "engine": "v2_lunar_month",
        "notes": "Sherpa purification festival, celebrates Guru Rinpoche.",
        "tags": ["v4", "sherpa", "buddhist"],
        "rule": {"lunar_month": "Jestha", "tithi": 10, "paksha": "shukla", "adhik_policy": "skip"},
    },
    {
        "festival_id": "swayambhu-purnima",
        "name_en": "Swayambhu Purnima",
        "name_ne": "स्वयम्भू पूर्णिमा",
        "rule_type": "lunar",
        "status": "computed",
        "confidence": "medium",
        "category": "buddhist",
        "importance": "local",
        "tradition": "newar_buddhist",
        "regions": ["kathmandu", "swayambhu"],
        "rule_family": "lunar_month_tithi",
        "profile_ids": [],
        "has_variant_profiles": False,
        "source": "expansion_v4",
        "engine": "v2_lunar_month",
        "notes": "Full moon pilgrimage to Swayambhunath stupa.",
        "tags": ["v4", "buddhist", "newari"],
        "rule": {"lunar_month": "Baishakh", "tithi": 15, "paksha": "shukla", "adhik_policy": "skip"},
    },
    {
        "festival_id": "prajnaparamita-day",
        "name_en": "Prajnaparamita Day",
        "name_ne": "प्रज्ञापारमिता दिवस",
        "rule_type": "lunar",
        "status": "computed",
        "confidence": "medium",
        "category": "buddhist",
        "importance": "observance",
        "tradition": "mahayana",
        "regions": ["lumbini", "boudha"],
        "rule_family": "lunar_month_tithi",
        "profile_ids": [],
        "has_variant_profiles": False,
        "source": "expansion_v4",
        "engine": "v2_lunar_month",
        "notes": "Perfection of Wisdom sutra recitation day.",
        "tags": ["v4", "buddhist", "mahayana"],
        "rule": {"lunar_month": "Magh", "tithi": 8, "paksha": "shukla", "adhik_policy": "skip"},
    },
    {
        "festival_id": "sangha-day",
        "name_en": "Sangha Day (Magha Puja)",
        "name_ne": "सङ्घ दिवस",
        "rule_type": "lunar",
        "status": "computed",
        "confidence": "medium",
        "category": "buddhist",
        "importance": "observance",
        "tradition": "theravada",
        "regions": ["lumbini"],
        "rule_family": "lunar_month_tithi",
        "profile_ids": [],
        "has_variant_profiles": False,
        "source": "expansion_v4",
        "engine": "v2_lunar_month",
        "notes": "Assembly of 1250 Arahants. Magha Purnima.",
        "tags": ["v4", "buddhist"],
        "rule": {"lunar_month": "Magh", "tithi": 15, "paksha": "shukla", "adhik_policy": "skip"},
    },

    # ═══════════════════════════════════════════════════════
    # KIRAT / RAI / LIMBU FESTIVALS (12 new)
    # ═══════════════════════════════════════════════════════
    {
        "festival_id": "sakela-sili",
        "name_en": "Sakela Sili (Sakewa)",
        "name_ne": "साकेला सिलि",
        "rule_type": "lunar",
        "status": "computed",
        "confidence": "high",
        "category": "kirat",
        "importance": "major",
        "tradition": "rai",
        "regions": ["solukhumbu", "bhojpur", "khotang", "udayapur"],
        "rule_family": "lunar_month_tithi",
        "profile_ids": [],
        "has_variant_profiles": True,
        "source": "expansion_v4",
        "engine": "v2_lunar_month",
        "notes": "Rai nature worship festival with Sili dance. Baishakh Purnima.",
        "tags": ["v4", "kirat", "rai"],
        "rule": {"lunar_month": "Baishakh", "tithi": 15, "paksha": "shukla", "adhik_policy": "skip"},
    },
    {
        "festival_id": "udhauli",
        "name_en": "Udhauli",
        "name_ne": "उधौली",
        "rule_type": "lunar",
        "status": "computed",
        "confidence": "high",
        "category": "kirat",
        "importance": "major",
        "tradition": "kirat",
        "regions": ["solukhumbu", "bhojpur", "khotang", "dhankuta"],
        "rule_family": "lunar_month_tithi",
        "profile_ids": [],
        "has_variant_profiles": False,
        "source": "expansion_v4",
        "engine": "v2_lunar_month",
        "notes": "Kirat downhill migration festival. Mangsir Purnima.",
        "tags": ["v4", "kirat"],
        "rule": {"lunar_month": "Mangsir", "tithi": 15, "paksha": "shukla", "adhik_policy": "skip"},
    },
    {
        "festival_id": "chasok-tangnam",
        "name_en": "Chasok Tangnam",
        "name_ne": "छासोक ताङ्नाम",
        "rule_type": "lunar",
        "status": "computed",
        "confidence": "medium",
        "category": "kirat",
        "importance": "regional",
        "tradition": "limbu",
        "regions": ["taplejung", "panchthar", "ilam"],
        "rule_family": "lunar_month_tithi",
        "profile_ids": [],
        "has_variant_profiles": False,
        "source": "expansion_v4",
        "engine": "v2_lunar_month",
        "notes": "Limbu harvest thanksgiving festival. Mangsir new moon.",
        "tags": ["v4", "limbu", "kirat"],
        "rule": {"lunar_month": "Mangsir", "tithi": 1, "paksha": "krishna", "adhik_policy": "skip"},
    },
    {
        "festival_id": "tamu-lhosar",
        "name_en": "Tamu Lhosar",
        "name_ne": "तमु ल्होसार",
        "rule_type": "bs_fixed",
        "status": "computed",
        "confidence": "high",
        "category": "kirat",
        "importance": "national",
        "tradition": "gurung",
        "regions": ["kaski", "lamjung", "gorkha", "tanahu"],
        "rule_family": "bs_fixed_date",
        "profile_ids": [],
        "has_variant_profiles": False,
        "source": "expansion_v4",
        "engine": "v2_bs_fixed",
        "notes": "Gurung New Year. 15 Poush (29-30 Dec).",
        "tags": ["v4", "gurung", "lhosar"],
        "rule": {"bs_month": 9, "bs_day": 15},
    },
    {
        "festival_id": "yokwa",
        "name_en": "Yokwa (Rai Ancestor Worship)",
        "name_ne": "योक्वा",
        "rule_type": "lunar",
        "status": "computed",
        "confidence": "medium",
        "category": "kirat",
        "importance": "regional",
        "tradition": "rai",
        "regions": ["bhojpur", "khotang"],
        "rule_family": "lunar_month_tithi",
        "profile_ids": [],
        "has_variant_profiles": False,
        "source": "expansion_v4",
        "engine": "v2_lunar_month",
        "notes": "Rai ancestor worship, propitiation of Sumnima-Paruhang.",
        "tags": ["v4", "rai", "kirat"],
        "rule": {"lunar_month": "Kartik", "tithi": 1, "paksha": "shukla", "adhik_policy": "skip"},
    },
    {
        "festival_id": "sakela-ubhauli",
        "name_en": "Sakela Ubhauli",
        "name_ne": "साकेला उभौली",
        "rule_type": "lunar",
        "status": "computed",
        "confidence": "high",
        "category": "kirat",
        "importance": "major",
        "tradition": "rai",
        "regions": ["solukhumbu", "bhojpur", "khotang"],
        "rule_family": "lunar_month_tithi",
        "profile_ids": [],
        "has_variant_profiles": False,
        "source": "expansion_v4",
        "engine": "v2_lunar_month",
        "notes": "Spring Sakela with uphill migration dances.",
        "tags": ["v4", "rai", "kirat"],
        "rule": {"lunar_month": "Baishakh", "tithi": 15, "paksha": "shukla", "adhik_policy": "skip"},
    },
    {
        "festival_id": "bal-chaturdashi-kirat",
        "name_en": "Bala Chaturdashi (Kirat)",
        "name_ne": "बाला चतुर्दशी (किरात)",
        "rule_type": "lunar",
        "status": "computed",
        "confidence": "high",
        "category": "kirat",
        "importance": "regional",
        "tradition": "kirat",
        "regions": ["eastern_nepal"],
        "rule_family": "lunar_month_tithi",
        "profile_ids": [],
        "has_variant_profiles": True,
        "source": "expansion_v4",
        "engine": "v2_lunar_month",
        "notes": "Kirat variant of Bala Chaturdashi at Halesi Mahadev.",
        "tags": ["v4", "kirat"],
        "rule": {"lunar_month": "Mangsir", "tithi": 14, "paksha": "krishna", "adhik_policy": "skip"},
    },
    {
        "festival_id": "maghe-sakranti-limbu",
        "name_en": "Maghe Sankranti (Limbu)",
        "name_ne": "माघे संक्रान्ति (लिम्बू)",
        "rule_type": "bs_fixed",
        "status": "computed",
        "confidence": "high",
        "category": "kirat",
        "importance": "regional",
        "tradition": "limbu",
        "regions": ["taplejung", "panchthar", "ilam"],
        "rule_family": "bs_fixed_date",
        "profile_ids": [],
        "has_variant_profiles": True,
        "source": "expansion_v4",
        "engine": "v2_bs_fixed",
        "notes": "Limbu variant with Tongba and meat feasting.",
        "tags": ["v4", "limbu", "kirat"],
        "rule": {"bs_month": 10, "bs_day": 1},
    },
    {
        "festival_id": "sappok-chham",
        "name_en": "Sappok Chham (Limbu Death Ritual)",
        "name_ne": "सप्पोक छाम",
        "rule_type": "lunar",
        "status": "provisional",
        "confidence": "low",
        "category": "kirat",
        "importance": "observance",
        "tradition": "limbu",
        "regions": ["taplejung", "panchthar"],
        "rule_family": "lunar_bs_tithi",
        "profile_ids": [],
        "has_variant_profiles": False,
        "source": "expansion_v4",
        "engine": "v1_legacy",
        "notes": "Limbu ancestor propitiation with masked dances. Variable dates.",
        "tags": ["v4", "limbu", "kirat"],
        "rule": {"bs_month": 9, "tithi": 1, "paksha": "shukla"},
    },
    {
        "festival_id": "nwagi",
        "name_en": "Nwagi (New Rice Festival)",
        "name_ne": "न्वागी",
        "rule_type": "lunar",
        "status": "computed",
        "confidence": "medium",
        "category": "kirat",
        "importance": "regional",
        "tradition": "rai",
        "regions": ["bhojpur", "khotang", "udayapur"],
        "rule_family": "lunar_month_tithi",
        "profile_ids": [],
        "has_variant_profiles": False,
        "source": "expansion_v4",
        "engine": "v2_lunar_month",
        "notes": "Rai first rice eating ceremony. Mangsir Purnima.",
        "tags": ["v4", "rai", "kirat"],
        "rule": {"lunar_month": "Mangsir", "tithi": 15, "paksha": "shukla", "adhik_policy": "skip"},
    },
    {
        "festival_id": "mundhum-reading",
        "name_en": "Mundhum Recitation",
        "name_ne": "मुन्धुम वाचन",
        "rule_type": "lunar",
        "status": "provisional",
        "confidence": "low",
        "category": "kirat",
        "importance": "observance",
        "tradition": "kirat",
        "regions": ["eastern_nepal"],
        "rule_family": "lunar_bs_tithi",
        "profile_ids": [],
        "has_variant_profiles": False,
        "source": "expansion_v4",
        "engine": "v1_legacy",
        "notes": "Recitation of Kirat oral scripture. Variable by community.",
        "tags": ["v4", "kirat"],
        "rule": {"bs_month": 1, "tithi": 1, "paksha": "shukla"},
    },

    # ═══════════════════════════════════════════════════════
    # THARU / REGIONAL FESTIVALS (10 new)
    # ═══════════════════════════════════════════════════════
    {
        "festival_id": "maghi-tharu",
        "name_en": "Maghi (Tharu New Year)",
        "name_ne": "माघी (थारू नयाँ वर्ष)",
        "rule_type": "bs_fixed",
        "status": "computed",
        "confidence": "high",
        "category": "tharu",
        "importance": "major",
        "tradition": "tharu",
        "regions": ["kailali", "kanchanpur", "bardiya", "dang", "chitwan"],
        "rule_family": "bs_fixed_date",
        "profile_ids": [],
        "has_variant_profiles": False,
        "source": "expansion_v4",
        "engine": "v2_bs_fixed",
        "notes": "Tharu New Year on Magh 1. Bonfire, feasting, stick dance.",
        "tags": ["v4", "tharu"],
        "rule": {"bs_month": 10, "bs_day": 1},
    },
    {
        "festival_id": "jitiya",
        "name_en": "Jitiya (Jivitputrika)",
        "name_ne": "जितिया",
        "rule_type": "lunar",
        "status": "computed",
        "confidence": "high",
        "category": "tharu",
        "importance": "major",
        "tradition": "tharu",
        "regions": ["terai", "janakpur", "birgunj"],
        "rule_family": "lunar_month_tithi",
        "profile_ids": [],
        "has_variant_profiles": False,
        "source": "expansion_v4",
        "engine": "v2_lunar_month",
        "notes": "Mothers fast for children's wellbeing. Ashwin Krishna Ashtami.",
        "tags": ["v4", "tharu"],
        "rule": {"lunar_month": "Ashwin", "tithi": 8, "paksha": "krishna", "adhik_policy": "skip"},
    },
    {
        "festival_id": "astimki",
        "name_en": "Astimki",
        "name_ne": "अस्तिम्की",
        "rule_type": "lunar",
        "status": "computed",
        "confidence": "medium",
        "category": "tharu",
        "importance": "regional",
        "tradition": "tharu",
        "regions": ["dang", "banke"],
        "rule_family": "lunar_month_tithi",
        "profile_ids": [],
        "has_variant_profiles": False,
        "source": "expansion_v4",
        "engine": "v2_lunar_month",
        "notes": "Tharu community festival with gurau (shaman) rituals.",
        "tags": ["v4", "tharu"],
        "rule": {"lunar_month": "Kartik", "tithi": 8, "paksha": "krishna", "adhik_policy": "skip"},
    },
    {
        "festival_id": "atwari",
        "name_en": "Atwari",
        "name_ne": "अत्वारी",
        "rule_type": "lunar",
        "status": "computed",
        "confidence": "medium",
        "category": "tharu",
        "importance": "regional",
        "tradition": "tharu",
        "regions": ["chitwan", "nawalparasi"],
        "rule_family": "lunar_month_tithi",
        "profile_ids": [],
        "has_variant_profiles": False,
        "source": "expansion_v4",
        "engine": "v2_lunar_month",
        "notes": "Tharu harvest thanksgiving festival.",
        "tags": ["v4", "tharu"],
        "rule": {"lunar_month": "Magh", "tithi": 1, "paksha": "shukla", "adhik_policy": "skip"},
    },
    {
        "festival_id": "sakhewa-tharu",
        "name_en": "Sakhewa Puja",
        "name_ne": "सखेवा पूजा",
        "rule_type": "lunar",
        "status": "computed",
        "confidence": "medium",
        "category": "tharu",
        "importance": "regional",
        "tradition": "tharu",
        "regions": ["morang", "sunsari"],
        "rule_family": "lunar_month_tithi",
        "profile_ids": [],
        "has_variant_profiles": False,
        "source": "expansion_v4",
        "engine": "v2_lunar_month",
        "notes": "Eastern Tharu nature worship linked to Sal tree.",
        "tags": ["v4", "tharu"],
        "rule": {"lunar_month": "Baishakh", "tithi": 15, "paksha": "shukla", "adhik_policy": "skip"},
    },
    {
        "festival_id": "madi-jatra",
        "name_en": "Madi Jatra",
        "name_ne": "मादी जात्रा",
        "rule_type": "lunar",
        "status": "provisional",
        "confidence": "low",
        "category": "regional",
        "importance": "local",
        "tradition": "mixed",
        "regions": ["chitwan"],
        "rule_family": "lunar_bs_tithi",
        "profile_ids": [],
        "has_variant_profiles": False,
        "source": "expansion_v4",
        "engine": "v1_legacy",
        "notes": "Inner Terai agricultural festival.",
        "tags": ["v4", "regional"],
        "rule": {"bs_month": 1, "tithi": 1, "paksha": "shukla"},
    },
    {
        "festival_id": "gadhimai-festival",
        "name_en": "Gadhimai Festival",
        "name_ne": "गढीमाई पर्व",
        "rule_type": "lunar",
        "status": "computed",
        "confidence": "medium",
        "category": "regional",
        "importance": "regional",
        "tradition": "hindu_tharu",
        "regions": ["bara", "rautahat"],
        "rule_family": "lunar_month_tithi",
        "profile_ids": [],
        "has_variant_profiles": False,
        "source": "expansion_v4",
        "engine": "v2_lunar_month",
        "notes": "Every 5 years at Bariyarpur. Mangsir 1.",
        "tags": ["v4", "regional"],
        "rule": {"lunar_month": "Mangsir", "tithi": 1, "paksha": "shukla", "adhik_policy": "skip"},
    },
    {
        "festival_id": "ropain-jatra",
        "name_en": "Ropain Jatra (Rice Planting Day)",
        "name_ne": "रोपाईं जात्रा",
        "rule_type": "bs_fixed",
        "status": "computed",
        "confidence": "high",
        "category": "regional",
        "importance": "national",
        "tradition": "agricultural",
        "regions": ["all"],
        "rule_family": "bs_fixed_date",
        "profile_ids": [],
        "has_variant_profiles": False,
        "source": "expansion_v4",
        "engine": "v2_bs_fixed",
        "notes": "National Paddy Day. Ashar 15.",
        "tags": ["v4", "agricultural"],
        "rule": {"bs_month": 3, "bs_day": 15},
    },
    {
        "festival_id": "bhumi-puja",
        "name_en": "Bhumi Puja (Earth Worship)",
        "name_ne": "भूमि पूजा",
        "rule_type": "lunar",
        "status": "computed",
        "confidence": "medium",
        "category": "regional",
        "importance": "observance",
        "tradition": "agricultural",
        "regions": ["terai", "eastern_nepal"],
        "rule_family": "lunar_month_tithi",
        "profile_ids": [],
        "has_variant_profiles": False,
        "source": "expansion_v4",
        "engine": "v2_lunar_month",
        "notes": "Earth worship before planting season.",
        "tags": ["v4", "agricultural"],
        "rule": {"lunar_month": "Baishakh", "tithi": 3, "paksha": "shukla", "adhik_policy": "skip"},
    },
    {
        "festival_id": "ghatu-nachh",
        "name_en": "Ghatu Nachh (Gurung)",
        "name_ne": "घटु नाच",
        "rule_type": "lunar",
        "status": "computed",
        "confidence": "medium",
        "category": "regional",
        "importance": "regional",
        "tradition": "gurung",
        "regions": ["kaski", "lamjung", "tanahu"],
        "rule_family": "lunar_month_tithi",
        "profile_ids": [],
        "has_variant_profiles": False,
        "source": "expansion_v4",
        "engine": "v2_lunar_month",
        "notes": "Gurung trance dance festival. Baishakh Purnima.",
        "tags": ["v4", "gurung"],
        "rule": {"lunar_month": "Baishakh", "tithi": 15, "paksha": "shukla", "adhik_policy": "skip"},
    },

    # ═══════════════════════════════════════════════════════
    # ISLAMIC OBSERVANCES (5 new, tabular approximation)
    # ═══════════════════════════════════════════════════════
    {
        "festival_id": "eid-ul-fitr",
        "name_en": "Eid ul-Fitr",
        "name_ne": "ईद उल-फित्र",
        "rule_type": "islamic_lunar",
        "status": "provisional",
        "confidence": "low",
        "category": "islamic",
        "importance": "national",
        "tradition": "islamic",
        "regions": ["nepalgunj", "birgunj", "janakpur", "kathmandu"],
        "rule_family": "islamic_calendar",
        "profile_ids": [],
        "has_variant_profiles": False,
        "source": "expansion_v4",
        "engine": "v1_legacy",
        "notes": "End of Ramadan. Date depends on moon sighting. Shifts ~11 days earlier each Gregorian year.",
        "tags": ["v4", "islamic"],
        "rule": {"islamic_month": "Shawwal", "islamic_day": 1},
    },
    {
        "festival_id": "eid-ul-adha",
        "name_en": "Eid ul-Adha (Bakra Eid)",
        "name_ne": "ईद उल-अधा (बक्रा ईद)",
        "rule_type": "islamic_lunar",
        "status": "provisional",
        "confidence": "low",
        "category": "islamic",
        "importance": "national",
        "tradition": "islamic",
        "regions": ["nepalgunj", "birgunj", "janakpur"],
        "rule_family": "islamic_calendar",
        "profile_ids": [],
        "has_variant_profiles": False,
        "source": "expansion_v4",
        "engine": "v1_legacy",
        "notes": "Festival of sacrifice. 10 Dhul Hijjah.",
        "tags": ["v4", "islamic"],
        "rule": {"islamic_month": "Dhul Hijjah", "islamic_day": 10},
    },
    {
        "festival_id": "milad-un-nabi",
        "name_en": "Milad un-Nabi (Mawlid)",
        "name_ne": "मिलाद उन-नबी",
        "rule_type": "islamic_lunar",
        "status": "provisional",
        "confidence": "low",
        "category": "islamic",
        "importance": "regional",
        "tradition": "islamic",
        "regions": ["nepalgunj", "birgunj"],
        "rule_family": "islamic_calendar",
        "profile_ids": [],
        "has_variant_profiles": False,
        "source": "expansion_v4",
        "engine": "v1_legacy",
        "notes": "Birth of Prophet Muhammad. 12 Rabi ul-Awwal.",
        "tags": ["v4", "islamic"],
        "rule": {"islamic_month": "Rabi ul-Awwal", "islamic_day": 12},
    },
    {
        "festival_id": "ramadan-start",
        "name_en": "Ramadan Begins",
        "name_ne": "रमजान आरम्भ",
        "rule_type": "islamic_lunar",
        "status": "provisional",
        "confidence": "low",
        "category": "islamic",
        "importance": "major",
        "tradition": "islamic",
        "regions": ["nepalgunj", "birgunj", "janakpur"],
        "rule_family": "islamic_calendar",
        "profile_ids": [],
        "has_variant_profiles": False,
        "source": "expansion_v4",
        "engine": "v1_legacy",
        "notes": "Start of holy month of fasting.",
        "tags": ["v4", "islamic"],
        "rule": {"islamic_month": "Ramadan", "islamic_day": 1},
    },
    {
        "festival_id": "shab-e-barat",
        "name_en": "Shab-e-Barat",
        "name_ne": "शब-ए-बारात",
        "rule_type": "islamic_lunar",
        "status": "provisional",
        "confidence": "low",
        "category": "islamic",
        "importance": "observance",
        "tradition": "islamic",
        "regions": ["nepalgunj", "birgunj"],
        "rule_family": "islamic_calendar",
        "profile_ids": [],
        "has_variant_profiles": False,
        "source": "expansion_v4",
        "engine": "v1_legacy",
        "notes": "Night of forgiveness. 15 Shaban.",
        "tags": ["v4", "islamic"],
        "rule": {"islamic_month": "Shaban", "islamic_day": 15},
    },

    # ═══════════════════════════════════════════════════════
    # CROSS-TRADITION MULTI-FAITH (5 new)
    # ═══════════════════════════════════════════════════════
    {
        "festival_id": "lumbini-day",
        "name_en": "Lumbini Day (UNESCO Heritage)",
        "name_ne": "लुम्बिनी दिवस",
        "rule_type": "bs_fixed",
        "status": "computed",
        "confidence": "high",
        "category": "national",
        "importance": "national",
        "tradition": "multi_faith",
        "regions": ["lumbini", "all"],
        "rule_family": "bs_fixed_date",
        "profile_ids": [],
        "has_variant_profiles": False,
        "source": "expansion_v4",
        "engine": "v2_bs_fixed",
        "notes": "Celebrates Lumbini as Buddha's birthplace. Government holiday.",
        "tags": ["v4", "national", "buddhist"],
        "rule": {"bs_month": 9, "bs_day": 1},
    },
    {
        "festival_id": "janai-purnima-multi",
        "name_en": "Janai Purnima (Multi-tradition)",
        "name_ne": "जनै पूर्णिमा (बहु-सम्प्रदाय)",
        "rule_type": "lunar",
        "status": "computed",
        "confidence": "high",
        "category": "national",
        "importance": "national",
        "tradition": "multi_faith",
        "regions": ["all"],
        "rule_family": "lunar_month_tithi",
        "profile_ids": [],
        "has_variant_profiles": True,
        "source": "expansion_v4",
        "engine": "v2_lunar_month",
        "notes": "Sacred thread changing (Hindu) + Kwati soup (Newari) + pilgrimage. Shrawan Purnima.",
        "tags": ["v4", "multi_tradition"],
        "rule": {"lunar_month": "Shrawan", "tithi": 15, "paksha": "shukla", "adhik_policy": "skip"},
    },
    {
        "festival_id": "christmas-nepal",
        "name_en": "Christmas (Nepal)",
        "name_ne": "क्रिसमस",
        "rule_type": "gregorian_fixed",
        "status": "computed",
        "confidence": "high",
        "category": "national",
        "importance": "observance",
        "tradition": "christian",
        "regions": ["kathmandu", "pokhara"],
        "rule_family": "gregorian_fixed",
        "profile_ids": [],
        "has_variant_profiles": False,
        "source": "expansion_v4",
        "engine": "v2_gregorian",
        "notes": "Christian observance. Growing community in Nepal.",
        "tags": ["v4", "christian"],
        "rule": {"gregorian_month": 12, "gregorian_day": 25},
    },
    {
        "festival_id": "international-women-day",
        "name_en": "International Women's Day",
        "name_ne": "अन्तर्राष्ट्रिय महिला दिवस",
        "rule_type": "gregorian_fixed",
        "status": "computed",
        "confidence": "high",
        "category": "national",
        "importance": "observance",
        "tradition": "secular",
        "regions": ["all"],
        "rule_family": "gregorian_fixed",
        "profile_ids": [],
        "has_variant_profiles": False,
        "source": "expansion_v4",
        "engine": "v2_gregorian",
        "notes": "Observed nationally with rallies and programs.",
        "tags": ["v4", "secular"],
        "rule": {"gregorian_month": 3, "gregorian_day": 8},
    },
    {
        "festival_id": "loktantra-diwas",
        "name_en": "Loktantra Diwas (Democracy Day)",
        "name_ne": "लोकतन्त्र दिवस",
        "rule_type": "bs_fixed",
        "status": "computed",
        "confidence": "high",
        "category": "national",
        "importance": "national",
        "tradition": "secular",
        "regions": ["all"],
        "rule_family": "bs_fixed_date",
        "profile_ids": [],
        "has_variant_profiles": False,
        "source": "expansion_v4",
        "engine": "v2_bs_fixed",
        "notes": "Commemorates abolition of monarchy. Jestha 15.",
        "tags": ["v4", "national", "secular"],
        "rule": {"bs_month": 2, "bs_day": 15},
    },
]


def main():
    print(f"Loading {RULES_PATH}...")
    with open(RULES_PATH) as f:
        data = json.load(f)

    existing_ids = {r["festival_id"] for r in data["festivals"]}
    added = 0
    skipped = 0
    duplicates = []

    for rule in NEW_RULES:
        if rule["festival_id"] in existing_ids:
            skipped += 1
            duplicates.append(rule["festival_id"])
            continue
        data["festivals"].append(rule)
        existing_ids.add(rule["festival_id"])
        added += 1

    # Update metadata
    data["total_rules"] = len(data["festivals"])
    data["generated_at"] = datetime.now(timezone.utc).isoformat()

    # Count by category
    categories = {}
    for r in data["festivals"]:
        cat = r.get("category", "unknown")
        categories[cat] = categories.get(cat, 0) + 1

    with open(RULES_PATH, "w") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

    print(f"\n=== Results ===")
    print(f"Added: {added}")
    print(f"Skipped (duplicate): {skipped}")
    if duplicates:
        print(f"  Duplicates: {', '.join(duplicates)}")
    print(f"Total rules: {data['total_rules']}")
    print(f"\n=== Category breakdown ===")
    for cat, count in sorted(categories.items(), key=lambda x: -x[1]):
        print(f"  {cat}: {count}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
