export const endpointGroups = [
  { id: 'calendar', label: 'Calendar', description: 'Conversion, validation, today, and Panchanga' },
  { id: 'business', label: 'Business rules', description: 'Fiscal years, month lengths, and working days' },
  { id: 'festivals', label: 'Festivals', description: 'Festival discovery, dates, and timelines' },
  { id: 'planning', label: 'Planning', description: 'Muhurtas and place-aware temporal context' },
  { id: 'integrations', label: 'Integrations', description: 'Calendar feeds and upcoming events' },
  { id: 'platform', label: 'Platform', description: 'Policy and runtime readiness' },
  { id: 'future', label: 'Future BS', description: 'Research capability and model-risk boundaries' },
];

export const endpointCatalog = [
  {
    group: 'calendar',
    method: 'GET',
    path: '/v3/api/calendar/convert',
    title: 'AD to BS conversion',
    description: 'Convert a Gregorian date and return BS date, Tithi, provenance, and uncertainty.',
    tool: 'convert',
  },
  {
    group: 'calendar',
    method: 'POST',
    path: '/v3/api/calendar/bs-to-gregorian',
    title: 'BS to AD conversion',
    description: 'Convert a Bikram Sambat date to its Gregorian date with source metadata.',
    tool: 'convert',
  },
  {
    group: 'calendar',
    method: 'GET',
    path: '/v3/api/calendar/today',
    title: 'Today',
    description: 'Return the current AD and BS date with the active calendar policy.',
    tool: 'panchanga',
  },
  {
    group: 'calendar',
    method: 'GET',
    path: '/v3/api/calendar/dual-month',
    title: 'Dual-calendar month',
    description: 'Map every day in a Gregorian month to its Bikram Sambat equivalent.',
    route: '/panchanga',
  },
  {
    group: 'calendar',
    method: 'GET',
    path: '/v3/api/calendar/panchanga',
    title: 'Panchanga',
    description: 'Calculate Tithi, Nakshatra, Yoga, Karana, sunrise basis, and risk state.',
    tool: 'panchanga',
  },
  {
    group: 'calendar',
    method: 'GET',
    path: '/v3/api/calendar/validate-bs-date',
    title: 'Validate BS date',
    description: 'Check whether a BS day exists in the selected month and year.',
    tool: 'convert',
  },
  {
    group: 'business',
    method: 'GET',
    path: '/v3/api/enterprise/fiscal-year/{bs_year}',
    title: 'Fiscal-year boundaries',
    description: 'Resolve the AD and BS start and end of a Nepali fiscal year.',
    tool: 'fiscal',
  },
  {
    group: 'business',
    method: 'GET',
    path: '/v3/api/enterprise/bs-months/{bs_year}',
    title: 'Published BS months',
    description: 'Return all 12 month lengths and their source-backed status.',
    tool: 'fiscal',
  },
  {
    group: 'business',
    method: 'POST',
    path: '/v3/api/enterprise/business-days',
    title: 'Business-day count',
    description: 'Count working days between two BS dates under a weekend policy.',
    tool: 'fiscal',
  },
  {
    group: 'business',
    method: 'POST',
    path: '/v3/api/compliance/add-working-days',
    title: 'Add working days',
    description: 'Move a date by a signed number of working days under a compliance profile.',
    route: '/enterprise',
  },
  {
    group: 'business',
    method: 'POST',
    path: '/v3/api/compliance/evaluate-date',
    title: 'Evaluate a date',
    description: 'Evaluate a BS or AD date against a named compliance profile.',
    route: '/enterprise',
  },
  {
    group: 'festivals',
    method: 'GET',
    path: '/v3/api/festivals',
    title: 'Festival catalog',
    description: 'Search and filter the source-aware festival catalog.',
    tool: 'festivals',
  },
  {
    group: 'festivals',
    method: 'GET',
    path: '/v3/api/festivals/{festival_id}',
    title: 'Festival detail',
    description: 'Return the meaning, calculation method, dates, and nearby observances.',
    route: '/festivals',
  },
  {
    group: 'festivals',
    method: 'GET',
    path: '/v3/api/festivals/on-date/{date}',
    title: 'Festivals on date',
    description: 'Find observances that fall on a specific Gregorian date.',
    route: '/festivals',
  },
  {
    group: 'festivals',
    method: 'GET',
    path: '/v3/api/festivals/timeline',
    title: 'Festival timeline',
    description: 'Group festival results across a date range for calendar interfaces.',
    route: '/festivals',
  },
  {
    group: 'festivals',
    method: 'GET',
    path: '/v3/api/festivals/upcoming',
    title: 'Upcoming festivals',
    description: 'Return the next source-qualified observances inside a chosen window.',
    tool: 'festivals',
  },
  {
    group: 'planning',
    method: 'GET',
    path: '/v3/api/muhurta/calendar',
    title: 'Muhurta calendar',
    description: 'Rank timing windows over a date range for a place and intent.',
    route: '/best-time',
  },
  {
    group: 'planning',
    method: 'POST',
    path: '/v3/api/muhurta/heatmap',
    title: 'Muhurta heatmap',
    description: 'Score the day into useful, neutral, and caution timing blocks.',
    route: '/best-time',
  },
  {
    group: 'planning',
    method: 'POST',
    path: '/v3/api/temporal/compass',
    title: 'Temporal compass',
    description: 'Combine place, date, Panchanga, sunrise, and timing context.',
    route: '/today',
  },
  {
    group: 'integrations',
    method: 'GET',
    path: '/v3/api/feeds/all.ics',
    title: 'Calendar feed',
    description: 'Subscribe to a generated iCalendar feed of supported observances.',
    route: '/integrations',
  },
  {
    group: 'integrations',
    method: 'GET',
    path: '/v3/api/feeds/next',
    title: 'Feed preview',
    description: 'Preview the next events before adding a calendar subscription.',
    route: '/integrations',
  },
  {
    group: 'platform',
    method: 'GET',
    path: '/v3/api/policy',
    title: 'API policy',
    description: 'Read the active advisory, authority, and publication boundaries.',
    route: '/policy',
  },
  {
    group: 'platform',
    method: 'GET',
    path: '/health/ready',
    title: 'Readiness',
    description: 'Check whether required runtime dependencies are ready to serve requests.',
    docsOnly: true,
  },
  {
    group: 'future',
    method: 'GET',
    path: '/v4/api/future-bs/capabilities',
    title: 'Future-BS capability',
    description: 'Expose the public research scope and computed-prediction claim boundary.',
    tool: 'future',
  },
  {
    group: 'future',
    method: 'GET',
    path: '/v5/api/calendar-model-risk/capabilities',
    title: 'Calendar model risk',
    description: 'Describe calendar model-risk controls without exposing private research routes.',
    tool: 'future',
  },
];
